// Mocks generated by Mockito 5.4.4 from annotations
// in alert/test/features/edit_note/presentation/edit_note_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:alert/core/entities/note_entity.dart' as _i7;
import 'package:alert/core/error/failure.dart' as _i6;
import 'package:alert/features/edit_note/domain/repository/edit_note_repository.dart'
    as _i2;
import 'package:alert/features/edit_note/domain/usecase/edit_note.dart' as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEditNoteRepository_0 extends _i1.SmartFake
    implements _i2.EditNoteRepository {
  _FakeEditNoteRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EditNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditNote extends _i1.Mock implements _i4.EditNote {
  @override
  _i2.EditNoteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeEditNoteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeEditNoteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.EditNoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i7.NoteEntity? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [note],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [note],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, void>>.value(
                _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [note],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
